import type { ProcessingCapabilityScope } from '../processing-client'

export function createViewerCapabilityScopeFixture(): ProcessingCapabilityScope {
  return {
    scope: 'viewer',
    phase: 'viewer-backend-first',
    jobTypes: [
      { jobType: 'UPLOAD_INTAKE_ANALYSIS', implemented: true },
      { jobType: 'MEDIA_PREVIEW', implemented: true },
      { jobType: 'IMAGE_CONVERT', implemented: true },
      { jobType: 'OFFICE_CONVERT', implemented: true },
      { jobType: 'DOCUMENT_PREVIEW', implemented: true },
      { jobType: 'METADATA_EXPORT', implemented: true },
      { jobType: 'VIEWER_RESOLVE', implemented: true },
    ],
    notes: [],
    viewerMatrix: {
      acceptAttribute:
        '.jpg,.jpeg,.png,.webp,.avif,.gif,.bmp,.svg,.ico,.heic,.heif,.tiff,.tif,.raw,.dng,.cr2,.cr3,.nef,.arw,.raf,.rw2,.orf,.pef,.srw,.pdf,.txt,.csv,.html,.htm,.rtf,.doc,.docx,.odt,.xls,.xlsx,.pptx,.epub,.db,.sqlite,.mp4,.mov,.webm,.avi,.mkv,.wmv,.flv,.mp3,.wav,.ogg,.opus,.aac,.flac,.aiff,.aif',
      formats: [
        viewerFormat('jpg', [], 'JPG', 'image', ['image/jpeg'], 'browser-native', 'native-image'),
        viewerFormat('jpeg', [], 'JPEG', 'image', ['image/jpeg'], 'browser-native', 'native-image'),
        viewerFormat('png', [], 'PNG', 'image', ['image/png'], 'browser-native', 'native-image'),
        viewerFormat('webp', [], 'WebP', 'image', ['image/webp'], 'browser-native', 'native-image'),
        viewerFormat('avif', [], 'AVIF', 'image', ['image/avif'], 'browser-native', 'native-image'),
        viewerFormat('gif', [], 'GIF', 'image', ['image/gif'], 'browser-native', 'native-image'),
        viewerFormat('bmp', [], 'BMP', 'image', ['image/bmp'], 'browser-native', 'native-image'),
        viewerFormat('svg', [], 'SVG', 'image', ['image/svg+xml'], 'browser-native', 'native-image'),
        viewerFormat('ico', [], 'ICO', 'image', ['image/x-icon'], 'browser-native', 'native-image'),
        viewerFormat('heic', ['heif'], 'HEIC', 'image', ['image/heic', 'image/heif'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'IMAGE_CONVERT', 'METADATA_EXPORT']),
        viewerFormat('tiff', ['tif'], 'TIFF', 'image', ['image/tiff'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'IMAGE_CONVERT', 'METADATA_EXPORT']),
        viewerFormat('raw', ['dng', 'cr2', 'cr3', 'nef', 'arw', 'raf', 'rw2', 'orf', 'pef', 'srw'], 'RAW', 'image', [], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'IMAGE_CONVERT', 'METADATA_EXPORT']),
        viewerFormat('pdf', [], 'PDF', 'document', ['application/pdf'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('txt', [], 'TXT', 'document', ['text/plain'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('csv', [], 'CSV', 'document', ['text/csv'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('html', ['htm'], 'HTML', 'document', ['text/html'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('rtf', [], 'RTF', 'document', ['application/rtf'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('doc', [], 'DOC', 'document', ['application/msword'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('docx', [], 'DOCX', 'document', ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('odt', [], 'ODT', 'document', ['application/vnd.oasis.opendocument.text'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('xls', [], 'XLS', 'document', ['application/vnd.ms-excel'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('xlsx', [], 'XLSX', 'document', ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('pptx', [], 'PPTX', 'document', ['application/vnd.openxmlformats-officedocument.presentationml.presentation'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('epub', [], 'EPUB', 'document', ['application/epub+zip'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('db', [], 'DB', 'document', ['application/octet-stream'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('sqlite', [], 'SQLite', 'document', ['application/x-sqlite3'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'DOCUMENT_PREVIEW']),
        viewerFormat('mp4', [], 'MP4', 'media', ['video/mp4'], 'browser-native', 'native-video'),
        viewerFormat('mov', [], 'MOV', 'media', ['video/quicktime'], 'browser-native', 'native-video'),
        viewerFormat('webm', [], 'WebM', 'media', ['video/webm'], 'browser-native', 'native-video'),
        viewerFormat('avi', [], 'AVI', 'media', ['video/x-msvideo'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW']),
        viewerFormat('mkv', [], 'MKV', 'media', ['video/x-matroska'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW']),
        viewerFormat('wmv', [], 'WMV', 'media', ['video/x-ms-wmv'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW']),
        viewerFormat('flv', [], 'FLV', 'media', ['video/x-flv'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW']),
        viewerFormat('mp3', [], 'MP3', 'audio', ['audio/mpeg'], 'browser-native', 'native-audio'),
        viewerFormat('wav', [], 'WAV', 'audio', ['audio/wav'], 'browser-native', 'native-audio'),
        viewerFormat('ogg', [], 'OGG', 'audio', ['audio/ogg'], 'browser-native', 'native-audio'),
        viewerFormat('opus', [], 'OPUS', 'audio', ['audio/opus'], 'browser-native', 'native-audio'),
        viewerFormat('aac', [], 'AAC', 'audio', ['audio/aac'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW', 'METADATA_EXPORT']),
        viewerFormat('flac', [], 'FLAC', 'audio', ['audio/flac'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW', 'METADATA_EXPORT']),
        viewerFormat('aiff', ['aif'], 'AIFF', 'audio', ['audio/aiff'], 'server-assisted', 'server-viewer', ['VIEWER_RESOLVE', 'MEDIA_PREVIEW', 'METADATA_EXPORT']),
      ],
    },
    converterMatrix: null,
  }
}

export function createConverterCapabilityScopeFixture(): ProcessingCapabilityScope {
  return {
    scope: 'converter',
    phase: 'converter-backend-first',
    jobTypes: [
      { jobType: 'UPLOAD_INTAKE_ANALYSIS', implemented: true },
      { jobType: 'IMAGE_CONVERT', implemented: true },
      { jobType: 'OFFICE_CONVERT', implemented: true },
      { jobType: 'MEDIA_PREVIEW', implemented: true },
      { jobType: 'MEDIA_CONVERT', implemented: true },
      { jobType: 'DOCUMENT_PREVIEW', implemented: true },
      { jobType: 'METADATA_EXPORT', implemented: true },
    ],
    notes: [],
    viewerMatrix: null,
    converterMatrix: {
      acceptAttribute:
        '.jpg,.jpeg,.png,.webp,.bmp,.svg,.psd,.ai,.eps,.ps,.heic,.heif,.tiff,.tif,.raw,.dng,.cr2,.cr3,.nef,.arw,.raf,.rw2,.orf,.pef,.srw,.pdf,.doc,.docx,.rtf,.odt,.csv,.xlsx,.ods,.pptx,.mp4,.mov,.mkv,.avi,.webm,.wav,.flac,.mp3,.m4a',
      sourceFormats: [
        converterSource('jpg', ['jpeg'], 'JPG', 'native-raster', ['image/jpeg'], 'image', ['IMAGE_CONVERT']),
        converterSource('png', [], 'PNG', 'native-raster', ['image/png'], 'image', ['IMAGE_CONVERT']),
        converterSource('webp', [], 'WebP', 'native-raster', ['image/webp'], 'image', ['IMAGE_CONVERT']),
        converterSource('bmp', [], 'BMP', 'native-raster', ['image/bmp'], 'image', ['IMAGE_CONVERT']),
        converterSource('svg', [], 'SVG', 'native-raster', ['image/svg+xml'], 'image', ['IMAGE_CONVERT']),
        converterSource('psd', [], 'PSD', 'psd-raster', [], 'image', ['IMAGE_CONVERT']),
        converterSource('ai', [], 'AI', 'illustration-raster', [], 'image', ['IMAGE_CONVERT']),
        converterSource('eps', ['ps'], 'EPS', 'illustration-raster', [], 'image', ['IMAGE_CONVERT']),
        converterSource('heic', ['heif'], 'HEIC', 'heic-raster', ['image/heic', 'image/heif'], 'image', ['IMAGE_CONVERT']),
        converterSource('tiff', ['tif'], 'TIFF', 'tiff-raster', ['image/tiff'], 'image', ['IMAGE_CONVERT']),
        converterSource('raw', ['dng', 'cr2', 'cr3', 'nef', 'arw', 'raf', 'rw2', 'orf', 'pef', 'srw'], 'RAW', 'raw-raster', [], 'image', ['IMAGE_CONVERT']),
        converterSource('pdf', [], 'PDF', 'pdf-document', ['application/pdf'], 'document', ['OFFICE_CONVERT']),
        converterSource('doc', [], 'DOC', 'office-document', ['application/msword'], 'document', ['OFFICE_CONVERT']),
        converterSource('docx', [], 'DOCX', 'office-document', ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'], 'document', ['OFFICE_CONVERT']),
        converterSource('rtf', [], 'RTF', 'office-document', ['application/rtf'], 'document', ['OFFICE_CONVERT']),
        converterSource('odt', [], 'ODT', 'office-document', ['application/vnd.oasis.opendocument.text'], 'document', ['OFFICE_CONVERT']),
        converterSource('csv', [], 'CSV', 'spreadsheet-document', ['text/csv'], 'document', ['OFFICE_CONVERT']),
        converterSource('xlsx', [], 'XLSX', 'spreadsheet-document', ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], 'document', ['OFFICE_CONVERT']),
        converterSource('ods', [], 'ODS', 'spreadsheet-document', ['application/vnd.oasis.opendocument.spreadsheet'], 'document', ['OFFICE_CONVERT']),
        converterSource('pptx', [], 'PPTX', 'presentation-document', ['application/vnd.openxmlformats-officedocument.presentationml.presentation'], 'document', ['OFFICE_CONVERT']),
        converterSource('mp4', [], 'MP4', 'video-media', ['video/mp4'], 'media', ['MEDIA_CONVERT']),
        converterSource('mov', [], 'MOV', 'video-media', ['video/quicktime'], 'media', ['MEDIA_CONVERT']),
        converterSource('mkv', [], 'MKV', 'video-media', ['video/x-matroska'], 'media', ['MEDIA_CONVERT']),
        converterSource('avi', [], 'AVI', 'video-media', ['video/x-msvideo'], 'media', ['MEDIA_CONVERT']),
        converterSource('webm', [], 'WebM', 'video-media', ['video/webm'], 'media', ['MEDIA_CONVERT']),
        converterSource('wav', [], 'WAV', 'audio-media', ['audio/wav'], 'media', ['MEDIA_CONVERT']),
        converterSource('flac', [], 'FLAC', 'audio-media', ['audio/flac'], 'media', ['MEDIA_CONVERT']),
        converterSource('mp3', [], 'MP3', 'audio-media', ['audio/mpeg'], 'media', ['MEDIA_CONVERT']),
        converterSource('m4a', [], 'M4A', 'audio-media', ['audio/mp4'], 'media', ['MEDIA_CONVERT']),
      ],
      targetFormats: [
        converterTarget('jpg', 'JPG', 'image', 'image/jpeg', 'jpeg-encoder', true, false, 0.9, []),
        converterTarget('png', 'PNG', 'image', 'image/png', 'png-encoder', false, true, null, []),
        converterTarget('webp', 'WebP', 'image', 'image/webp', 'webp-encoder', true, true, 0.9, []),
        converterTarget('avif', 'AVIF', 'image', 'image/avif', 'avif-encoder', true, true, 0.78, []),
        converterTarget('svg', 'SVG', 'image', 'image/svg+xml', 'svg-vectorizer', false, true, null, []),
        converterTarget('ico', 'ICO', 'image', 'image/x-icon', 'ico-image', false, true, null, []),
        converterTarget('pdf', 'PDF', 'document', 'application/pdf', 'pdf-document', false, false, null, []),
        converterTarget('tiff', 'TIFF', 'image', 'image/tiff', 'tiff-image', false, true, null, []),
        converterTarget('docx', 'DOCX', 'document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx-document', false, true, null, []),
        converterTarget('txt', 'TXT', 'document', 'text/plain', 'txt-document', false, true, null, []),
        converterTarget('html', 'HTML', 'document', 'text/html', 'html-document', false, true, null, []),
        converterTarget('rtf', 'RTF', 'document', 'application/rtf', 'rtf-document', false, true, null, []),
        converterTarget('odt', 'ODT', 'document', 'application/vnd.oasis.opendocument.text', 'odt-document', false, true, null, []),
        converterTarget('xlsx', 'XLSX', 'document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx-document', false, true, null, []),
        converterTarget('csv', 'CSV', 'document', 'text/csv', 'csv-document', false, true, null, []),
        converterTarget('ods', 'ODS', 'document', 'application/vnd.oasis.opendocument.spreadsheet', 'ods-document', false, true, null, []),
        converterTarget('pptx', 'PPTX', 'document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'pptx-document', false, true, null, []),
        converterTarget('mp4', 'MP4', 'media', 'video/mp4', 'mp4-video', false, true, null, []),
        converterTarget('webm', 'WebM', 'media', 'video/webm', 'webm-video', false, true, null, []),
        converterTarget('gif', 'GIF', 'image', 'image/gif', 'gif-image', false, true, null, []),
        converterTarget('mp3', 'MP3', 'media', 'audio/mpeg', 'mp3-audio', false, true, null, []),
        converterTarget('wav', 'WAV', 'media', 'audio/wav', 'wav-audio', false, true, null, []),
        converterTarget('aac', 'AAC', 'media', 'audio/aac', 'aac-audio', false, true, null, []),
        converterTarget('m4a', 'M4A', 'media', 'audio/mp4', 'm4a-audio', false, true, null, []),
        converterTarget('flac', 'FLAC', 'media', 'audio/flac', 'flac-audio', false, true, null, []),
      ],
      scenarios: [
        converterScenario('heic', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('heic', 'avif', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('heic', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'webp', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'avif', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'svg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'ico', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('jpg', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('jpg', 'webp', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('jpg', 'avif', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('jpg', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('webp', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('webp', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('webp', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('bmp', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('bmp', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('bmp', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('psd', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('psd', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('psd', 'webp', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('tiff', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('tiff', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('tiff', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('raw', 'jpg', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('raw', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('raw', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('jpg', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('png', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('webp', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('bmp', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('heic', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('svg', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('svg', 'ico', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('svg', 'tiff', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('svg', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('ai', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('ai', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('eps', 'png', 'image', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('eps', 'pdf', 'document', 'server-assisted', ['IMAGE_CONVERT']),
        converterScenario('doc', 'docx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('docx', 'pdf', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'docx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('docx', 'txt', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('docx', 'html', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('rtf', 'docx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('docx', 'rtf', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('odt', 'docx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('docx', 'odt', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'jpg', 'image', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'png', 'image', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'txt', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'xlsx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'csv', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pdf', 'pptx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('xlsx', 'csv', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('csv', 'xlsx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('xlsx', 'pdf', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('ods', 'xlsx', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('xlsx', 'ods', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pptx', 'pdf', 'document', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pptx', 'jpg', 'image', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pptx', 'png', 'image', 'server-assisted', ['OFFICE_CONVERT']),
        converterScenario('pptx', 'mp4', 'media', 'server-assisted', ['OFFICE_CONVERT', 'MEDIA_PREVIEW']),
        converterScenario('mov', 'mp4', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mkv', 'mp4', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('avi', 'mp4', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('webm', 'mp4', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'mp4', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'webm', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mov', 'gif', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mkv', 'gif', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('avi', 'gif', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('webm', 'gif', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'gif', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mov', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mov', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mov', 'aac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mkv', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mkv', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mkv', 'aac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('avi', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('avi', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('avi', 'aac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('webm', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('webm', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('webm', 'aac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp4', 'aac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('wav', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('wav', 'flac', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('flac', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('flac', 'wav', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('m4a', 'mp3', 'media', 'server-assisted', ['MEDIA_CONVERT']),
        converterScenario('mp3', 'm4a', 'media', 'server-assisted', ['MEDIA_CONVERT']),
      ],
      presets: [
        converterPreset('original', 'Original', null, null, null, '#ffffff'),
        converterPreset('web-balanced', 'Web Balanced', 2560, 2560, 0.86, '#ffffff'),
        converterPreset('email-attachment', 'Email Attachment', 1600, 1600, 0.78, '#fffaf0'),
        converterPreset('thumbnail', 'Thumbnail', 512, 512, 0.72, '#f3ede3'),
      ],
    },
  }
}

export function createPlatformCapabilityScopeFixture(): ProcessingCapabilityScope {
  return {
    scope: 'platform',
    phase: 'processing-platform',
    jobTypes: [
      { jobType: 'UPLOAD_INTAKE_ANALYSIS', implemented: true },
      { jobType: 'MEDIA_PREVIEW', implemented: true },
      { jobType: 'MEDIA_CONVERT', implemented: true },
      { jobType: 'IMAGE_CONVERT', implemented: true },
      { jobType: 'DOCUMENT_PREVIEW', implemented: true },
      { jobType: 'METADATA_EXPORT', implemented: true },
      { jobType: 'VIEWER_RESOLVE', implemented: true },
    ],
    notes: [],
    viewerMatrix: null,
    converterMatrix: null,
    platformMatrix: {
      modules: [
        platformModule('compression', 'Compression', ['Target size', 'Quality', 'Batch'], ['IMAGE_CONVERT', 'MEDIA_CONVERT', 'MEDIA_PREVIEW']),
        platformModule('pdf-toolkit', 'PDF Toolkit', ['Merge', 'Rotate', 'Protect'], ['DOCUMENT_PREVIEW', 'IMAGE_CONVERT', 'VIEWER_RESOLVE']),
        platformModule('multi-format-editor', 'Multi-Format Editor', ['Preview', 'Validate', 'Export'], ['DOCUMENT_PREVIEW', 'METADATA_EXPORT']),
        platformModule('batch-conversion', 'Batch Conversion', ['Queue', 'Reuse', 'Artifacts'], ['IMAGE_CONVERT']),
        platformModule('ocr', 'OCR', ['Extract', 'Search', 'Scan'], ['DOCUMENT_PREVIEW', 'IMAGE_CONVERT']),
        platformModule('office-pdf-conversion', 'Office/PDF Conversion', ['DOCX', 'PDF', 'Office'], ['OFFICE_CONVERT', 'DOCUMENT_PREVIEW']),
      ],
    },
  }
}

function viewerFormat(
  extension: string,
  aliases: string[],
  label: string,
  family: string,
  mimeTypes: string[],
  previewPipeline: string,
  previewStrategyId: string,
  requiredJobTypes: string[] = [],
) {
  return {
    extension,
    aliases,
    label,
    family,
    mimeTypes,
    previewPipeline,
    previewStrategyId,
    statusLabel: previewPipeline === 'browser-native' ? 'Browser preview' : 'Server preview',
    notes: `${label} capability fixture`,
    accents: [label],
    available: true,
    availabilityDetail: null,
    requiredJobTypes,
  }
}

function converterSource(
  extension: string,
  aliases: string[],
  label: string,
  sourceStrategyId: string,
  mimeTypes: string[],
  family = 'image',
  requiredJobTypes: string[] = [],
) {
  return {
    extension,
    aliases,
    label,
    family,
    mimeTypes,
    sourceStrategyId,
    statusLabel: requiredJobTypes.length ? 'Backend intake' : 'Browser raster',
    notes: `${label} source fixture`,
    accents: [label],
    available: true,
    availabilityDetail: null,
    requiredJobTypes,
  }
}

function converterTarget(
  extension: string,
  label: string,
  family: string,
  mimeType: string,
  targetStrategyId: string,
  supportsQuality: boolean,
  supportsTransparency: boolean,
  defaultQuality: number | null,
  requiredJobTypes: string[] = [],
) {
  return {
    extension,
    label,
    family,
    mimeType,
    targetStrategyId,
    supportsQuality,
    supportsTransparency,
    defaultQuality,
    statusLabel: requiredJobTypes.length ? 'Backend encode' : 'Browser-native',
    notes: `${label} target fixture`,
    accents: [label],
    available: true,
    availabilityDetail: null,
    requiredJobTypes,
  }
}

function converterScenario(
  sourceExtension: string,
  targetExtension: string,
  family = 'image',
  executionMode: 'browser-native' | 'server-assisted' = 'server-assisted',
  requiredJobTypes: string[] = executionMode === 'server-assisted' ? ['IMAGE_CONVERT'] : [],
) {
  return {
    id: `${sourceExtension}->${targetExtension}`,
    family,
    label: `${sourceExtension.toUpperCase()} -> ${targetExtension.toUpperCase()}`,
    sourceExtension,
    targetExtension,
    statusLabel: executionMode === 'server-assisted' ? 'Server-assisted' : 'Browser-native',
    notes: `${sourceExtension} -> ${targetExtension} scenario fixture`,
    accents: [sourceExtension.toUpperCase(), targetExtension.toUpperCase()],
    executionMode,
    available: true,
    availabilityDetail: null,
    requiredJobTypes,
  }
}

function converterPreset(
  id: string,
  label: string,
  maxWidth: number | null,
  maxHeight: number | null,
  preferredQuality: number | null,
  defaultBackgroundColor: string,
) {
  return {
    id,
    label,
    detail: `${label} preset fixture`,
    statusLabel: label,
    accents: [label],
    maxWidth,
    maxHeight,
    preferredQuality,
    defaultBackgroundColor,
    available: true,
    availabilityDetail: null,
  }
}

function platformModule(
  id: string,
  label: string,
  accents: string[],
  reusedJobTypes: string[],
) {
  return {
    id,
    label,
    summary: `${label} platform fixture`,
    detail: `${label} detail fixture`,
    statusLabel: 'Foundation ready',
    accents,
    reusedDomains: ['artifact-storage', 'job-orchestration'],
    reusedJobTypes,
    nextSlices: ['slice-1', 'slice-2'],
    foundationReady: true,
    availabilityDetail: null,
  }
}
