package com.keykomi.jack.processing.domain;

public enum ProcessingJobType {

	UPLOAD_INTAKE_ANALYSIS,
	MEDIA_PREVIEW,
	MEDIA_CONVERT,
	IMAGE_CONVERT,
	FILE_COMPRESS,
	PDF_TOOLKIT,
	OFFICE_CONVERT,
	DOCUMENT_PREVIEW,
	METADATA_EXPORT,
	VIEWER_RESOLVE,
	EDITOR_PROCESS

}
